[package]
name = "parse-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
duct.workspace = true
test-case.workspace = true
which.workspace = true
similar.workspace = true
console.workspace = true

mcrl2-sys.workspace = true