[package]
name = "parse-checker"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
duct.workspace = true
test-case.workspace = true
which.workspace = true
similar.workspace = true
console.workspace = true

mcrl2-sys.workspace = true