[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
http-body-util.workspace = true
duct.workspace = true
